### ISSUE TITLE
"aeron-mdc" sample's dockerfile maybe have some problem

### ISSUE THREAD

**Issue by bufengmobuganhuo** [eleventy7/aeron-cookbook-code#137]
hello! When I try to run your ‘aeron-mdc’ sample code, I found that there may be some problems. Your code is compiled with JDK17, but the image in the dockerfile is jdk16, which causes the following problems at runtime. 
![image](https://user-images.githubusercontent.com/38028085/149516746-9b55a9fb-3cc4-4e50-9633-8c19efd5a7b7.png)
here is the JDK version in aeron-mdc-publiser/Dockerfile:
![image](https://user-images.githubusercontent.com/38028085/149517003-4f8928d2-1689-4bc9-bd6a-2d1b055afc0f.png)

When I changed the JDK version of the code to 16, the image can run normally.
![image](https://user-images.githubusercontent.com/38028085/149516872-7579fd29-31d9-4cd6-b809-ac2bd3e40b59.png)

**Comment by eleventy7** [comment]
Hi - I have pushed an update to both the base docker image on docker.io and the code to use the correct JDK. The code samples are running fine with JDK17 now. Many thanks for the report.
