### ISSUE TITLE
how config channel for udp multicast, special the "interface" paramter, all subs can receive messages from pub?

### ISSUE THREAD

**Issue by sunbiaozj** [eleventy7/aeron-cookbook-code#147]
hi, I am trying to run a Basic Publisher/Subscriber pair on the same Multicast/Port. 
I want to know how config channel for udp multicast, special the "interface" paramter, all subs can receive messages from pub?
I have three matchines, I want to test aeron by udp multicast type, three matchines in one local network(lan),

pub matchineA ip 192.168.31.100,
sub1 matchineB ip 192.168.31.120,
sub2 matchineC ip 192.168.31.121,

aeron:udp?endpoint=XXXX:40456|interface=YYYY|ttl=16";
what XXXX config is right? what YYYY config is right?
thank you!

#ifconfig
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        ether 1c:36:bb:ed:a0:4b 
        inet6 fe80::b4:eaa7:461b:2d3d%en0 prefixlen 64 secured scopeid 0x5 
        inet 192.168.31.120 netmask 0xffffff00 broadcast 192.168.31.255
        nd6 options=201<PERFORMNUD,DAD>
        media: autoselect
        status: active

**Comment by eleventy7** [comment]
Hi - UDP multicast is outside the scope of Aeron Cookbook. You will typically need to use class D IP addresses and properly configured network infrastructure.
