### ISSUE TITLE
Sending messages/scheduling timers from onStart.

### ISSUE THREAD

**Issue by galaxychris** [eleventy7/aeron-cookbook-code#174]
Hi Shaun,

Apologies if this is the incorrect forum or if I may have overlooked something in my testing but in reference to the section [cluster-timers#alternative](https://aeroncookbook.com/aeron-cluster/cluster-timers/#alternative) of the cookbook there is mention of using the offer API on the cluster object from within the `onStart` lifecycle method. Whilst playing around with this I'm noticing that a `io.aeron.cluster.client.ClustedException` is being thrown by the `ClusteredServiceAgent` as it appears to be preventing any timers or messages from being sent during an active lifecycle stage (in this case "onStart").  There does seem to be quite a bit of recent activity in that class so perhaps this became recently enforced?

Cheers!

**Comment by eleventy7** [comment]
This is the right place to raise questions. 

The recommendation is just to grab hold of the cluster object during within the `onStart` lifecycle method, and then make use of the `offer` method later once normal operation begins. As you saw, you can't offer within `onStart` - I will clarify the docs. If you're looking to kick off some process at start, I'd rather consider looking at the `onSessionOpen` method - have it use a flag and send just once, for example within `ClusteredService` implementation:

```
    private boolean firstClient = true;
    ...
    @Override
    public void onSessionOpen(ClientSession session, long timestamp)
    {
        log.info("Cluster Client Session opened");
        if (firstClient) {
            cluster.offer(....); //or scheduleTimer
            firstClient = false;
        }
    }
```

**Comment by eleventy7** [comment]
I've added a new page for an approach to creating startup tasks and clarified the cluster timer page.

https://aeroncookbook.com/cookbook-content/aeron-cluster-startup-tasks/

**Comment by galaxychris** [comment]
Ah got it - thanks for the quick response/clarification and the new page is helpful - thanks!
