### ISSUE TITLE
Execution failed for task ':agrona:test'.

### ISSUE THREAD

**Issue by andre-fxcm** [eleventy7/aeron-cookbook-code#186]
tried on windows and osx with both java11 && java17, same failure

> ./gradlew
> Task :agrona:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agrona:test'.
> Could not resolve all files for configuration ':agrona:testRuntimeClasspath'.
   > Could not find org.junit.platform:junit-platform-launcher:.
     Required by:
         project :agrona

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
14 actionable tasks: 1 executed, 13 up-to-date

**Comment by eleventy7** [comment]
Hi - thanks for the report. I've not seen this before, but have added jUnit Platform to the dependencies. Please let me know if this solves it for you.

**Comment by andre-fxcm** [comment]
Hi! I pulled your changes but it was still the same issue for me, I fixed it for myself with this patch:
https://github.com/eleventy7/aeron-cookbook-code/pull/188
