### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by JulienBe** [eleventy7/aeron-cookbook-code#87]
Hey, sorry if that's a silly question, but I can't figure out where classes such as `RpcConnectRequestDecoder` are supposed to be coming from. I don't see them on the repo. 
Old version maybe ? 
But there are still being used

**Comment by JulienBe** [comment]
Ok if I understand correctly, they are being generated from `src/main/resources/sbe/sbe.xsd` using sbt-tool. Sorry for the noise :)

**Comment by eleventy7** [comment]
That's correct. SBE is a code generator, and the code will appear once this has been run.

**Comment by eleventy7** [comment]
I've added a note to https://aeroncookbook.com/step-by-step-rpc-server/protocol/ so that this is clearer.
